In [1]:
# stdlib imports --------------------------------------------------- #
import argparse
import dataclasses
import json
import functools
import logging
import pathlib
import time
import types
import typing
import uuid
from typing import Any, Literal

# 3rd-party imports necessary for processing ----------------------- #
import numpy as np
import numpy.typing as npt
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import sklearn
import pynwb
import upath
import zarr
import utils

In [2]:
session_id = '626791_2022-08-15'

session = utils.get_nwb(session_id, raise_on_missing=True, raise_on_bad_file=True) 

In [3]:
session 

root pynwb.file.NWBFile at 0x139910167395920
Fields:
  acquisition: {
    frametimes_eye_camera <class 'abc.Events'>,
    frametimes_front_camera <class 'abc.Events'>,
    frametimes_side_camera <class 'abc.Events'>,
    lick_sensor_events <class 'pynwb.base.TimeSeries'>
  }
  devices: {
    18005102491 <class 'pynwb.device.Device'>,
    18005121302 <class 'pynwb.device.Device'>,
    18005123131 <class 'pynwb.device.Device'>,
    18194810652 <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    probeA <class 'pynwb.ecephys.ElectrodeGroup'>,
    probeB <class 'pynwb.ecephys.ElectrodeGroup'>,
    probeC <class 'pynwb.ecephys.ElectrodeGroup'>,
    probeF <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  epochs: epochs <class 'pynwb.epoch.TimeIntervals'>
  experiment_description: visual-auditory task-switching behavior experiment
  experimenter: ['Jackie Kuyat']
  file_create_date: [datetime.datetime(2025, 1, 14, 5, 57, 34, 766707, tzinfo=tzutc())]
  identifier: d91a53aa-2fdc-49ef-b1f3-4766d2ae8637
  institution: Neural Circuits & Behavior | MindScope program | Allen Institute for Neural Dynamics
  intervals: {
    aud_rf_mapping_trials <class 'pynwb.epoch.TimeIntervals'>,
    epochs <class 'pynwb.epoch.TimeIntervals'>,
    performance <class 'pynwb.epoch.TimeIntervals'>,
    trials <class 'pynwb.epoch.TimeIntervals'>,
    vis_rf_mapping_trials <class 'pynwb.epoch.TimeIntervals'>
  }
  keywords: <StrDataset for HDF5 dataset "keywords": shape (14,), type "|O">
  lab: NP3
  processing: {
    behavior <class 'pynwb.base.ProcessingModule'>,
    ecephys <class 'pynwb.base.ProcessingModule'>
  }
  session_description: ecephys session (day 1) with behavioral task data (day 41) and video recording of behavior
  session_id: 626791_2022-08-15
  session_start_time: 2022-08-15 11:22:17-07:00
  source_script: https://github.com/samgale/DynamicRoutingTask/blob/main/DynamicRouting1.py
  source_script_file_name: https://github.com/AllenInstitute/npc_sessions/releases/tag/v0.0.261
  stimulus_notes: stage 5 ori tone
  subject: subject pynwb.file.Subject at 0x139910167381856
Fields:
  age: P146D
  age__reference: birth
  date_of_birth: 2022-03-22 00:00:00-07:00
  genotype: wt/wt
  sex: M
  species: Mus musculus
  strain: C57BL6J(NP)
  subject_id: 626791

  timestamps_reference_time: 2022-08-15 11:22:17-07:00
  trials: trials <class 'pynwb.epoch.TimeIntervals'>
  units: units <class 'pynwb.misc.Units'>

In [8]:
session.epochs[:].query('script_name == "DynamicRouting1"')[['start_time', 'stop_time']]

start_time  stop_time
id                       
0      80.0712   3698.306

In [10]:
session.trials.start_time[0], session.trials.stop_time[-1]

(np.float64(85.7625), np.float64(3682.84621))

In [9]:
session.units[:].obs_intervals

id
0       [[10.528832310745369, 4572.419075979189]]
1       [[10.528832310745369, 4572.419075979189]]
2       [[10.528832310745369, 4572.419075979189]]
3       [[10.528832310745369, 4572.419075979189]]
4       [[10.528832310745369, 4572.419075979189]]
                          ...                    
2929    [[10.532128779326872, 4572.417483664491]]
2930    [[10.532128779326872, 4572.417483664491]]
2931    [[10.532128779326872, 4572.417483664491]]
2932    [[10.532128779326872, 4572.417483664491]]
2933    [[10.532128779326872, 4572.417483664491]]
Name: obs_intervals, Length: 2934, dtype: object

In [10]:
# facial features 
session.processing['behavior']['lp_side_camera'][:]

ear_base_l_error   ear_base_l_likelihood  ear_base_l_temporal_norm  \
id                                                                           
0              79.406761  0.00014947830641176552                       NaN   
1               1.709469      0.9999853372573853                147.263260   
2               1.670960      0.9999844431877136                  0.136048   
3               1.653104      0.9999895095825195                  0.111020   
4               1.681913      0.9999918937683105                  0.087850   
...                  ...                     ...                       ...   
274247         13.828854      0.9981189966201782                  0.418787   
274248         18.926159      0.9999884366989136                  0.269085   
274249         12.030972      0.9984285831451416                  0.272066   
274250          5.817550       0.999864399433136                  0.624545   
274251          9.715143      0.9995598196983337                  0.268787   

              ear_base_l_x        ear_base_l_y  ear_tip_l_error  \
id                                                                
0       326.39984130859375  226.06680297851562        46.273556   
1       198.28065490722656  153.45864868164062         1.451260   
2       198.37628173828125  153.36187744140625         1.423392   
3       198.28030395507812   153.3060760498047         1.406104   
4       198.21377563476562   153.2487030029297         1.450814   
...                    ...                 ...              ...   
274247  197.90304565429688   155.9340362548828        11.539735   
274248  198.13414001464844   155.7961883544922        15.492024   
274249  197.89785766601562  155.93106079101562        10.050280   
274250  198.25413513183594   156.4440155029297         5.114799   
274251  198.06854248046875  156.63844299316406         8.288326   

         ear_tip_l_likelihood  ear_tip_l_temporal_norm         ear_tip_l_x  \
id                                                                           
0       0.0001733447570586577                      NaN   328.5680847167969   
1          0.9999924302101135               166.554764   208.5664520263672   
2          0.9999932050704956                 0.041109  208.58119201660156   
3          0.9999934434890747                 0.013086  208.56849670410156   
4          0.9999933242797852                 0.020279   208.5482177734375   
...                       ...                      ...                 ...   
274247     0.9999752640724182                 0.297119   206.9082489013672   
274248     0.9996631741523743                 0.833106  206.22271728515625   
274249     0.9997788667678833                 0.547152  206.08108520507812   
274250     0.9992676377296448                 0.343972  206.37762451171875   
274251     0.9997912049293518                 0.700387  207.04685974121094   

               ear_tip_l_y  ...  whisker_pad_l_side_likelihood  \
id                          ...                                  
0       245.94422912597656  ...         2.2040387293031927e-09   
1       130.44488525390625  ...             0.9997093081474304   
2       130.40650939941406  ...             0.9996731281280518   
3       130.40333557128906  ...             0.9996938109397888   
4        130.4032440185547  ...             0.9997517466545105   
...                    ...  ...                            ...   
274247   133.1383514404297  ...              0.998347818851471   
274248  132.66494750976562  ...             0.9980002641677856   
274249  133.19345092773438  ...             0.9986873865127563   
274250   133.3677520751953  ...             0.9981263875961304   
274251  133.57431030273438  ...             0.9996663331985474   

       whisker_pad_l_side_temporal_norm  whisker_pad_l_side_x  \
id                                                              
0                                   NaN     560.9180908203125   
1                            441.769165    144.07943

In [29]:
# pupil 

session.processing['behavior']['eye_tracking'][:].pupil_area.values
session.processing['behavior']['eye_tracking'][:].timestamps.values


array([       nan,    5.0789 ,    5.09557, ..., 4575.87333, 4575.88998,
       4575.90666])

In [20]:
# running

session.processing['behavior']['running_speed'].data[:]

session.processing['behavior']['running_speed'].timestamps[:]


array([  80.04944,   80.06596,   80.08257, ..., 4540.48717, 4540.50372,
       4540.5204 ])

In [15]:
# cross modal dprimes

session.intervals['performance'][:].cross_modal_dprime.values

array([2.9743649 , 1.99122532, 1.37395546, 0.        , 1.77479553,
       2.11251779])

In [34]:
# licks
# upper limit on duration, thresholding at 0.5s

session.processing['behavior']['licks'].data[:]
session.processing['behavior']['licks'].timestamps[:]

array([  27.98856,   28.85258,   36.4437 , ..., 3711.79002, 3711.87005,
       3711.94207])